# Impact Analysis Framework Configuration
# Scoring: 1 (Very Low) to 5 (Very High)

business_value:
  dimension: "Business Value"
  criteria:
    - name: "market_opportunity"
      description: "市場機会の大きさと成長性"
      weight: 0.4
      scoringGuide:
        1: "ニッチ市場または縮小市場（<10億円）"
        2: "小規模市場、限定的な成長性（10-50億円）"
        3: "中規模市場、安定した成長性（50-200億円）"
        4: "大規模市場、高い成長性（200-1000億円）"
        5: "巨大市場、急成長中（>1000億円）"

    - name: "competitive_advantage"
      description: "競合優位性の持続可能性"
      weight: 0.3
      scoringGuide:
        1: "明確な差別化要素なし、多数の競合"
        2: "一時的な優位性、模倣が容易"
        3: "中程度の差別化、一定の参入障壁"
        4: "強い差別化要素、高い参入障壁"
        5: "独自性が非常に高く、長期的な優位性"

    - name: "revenue_potential"
      description: "収益化の可能性と確実性"
      weight: 0.3
      scoringGuide:
        1: "収益化モデルが不明確"
        2: "将来的な収益化の可能性あり"
        3: "明確な収益化プラン、実証段階"
        4: "実績のある収益化モデル"
        5: "高収益性が実証済み、スケーラブル"

implementation_feasibility:
  dimension: "Implementation Feasibility"
  criteria:
    - name: "technical_complexity"
      description: "技術的実現の難易度"
      weight: 0.4
      scoringGuide:
        1: "既存技術で容易に実現可能"
        2: "一部新技術が必要、リスクは低い"
        3: "中程度の技術革新が必要"
        4: "高度な技術革新、不確実性あり"
        5: "画期的な技術ブレークスルーが必要"

    - name: "resource_requirements"
      description: "必要な資源（人、資金、時間）"
      weight: 0.3
      scoringGuide:
        1: "最小限のリソース（<500万円、<3ヶ月）"
        2: "少ないリソース（500万-2000万円、3-6ヶ月）"
        3: "中程度のリソース（2000万-1億円、6-12ヶ月）"
        4: "大きなリソース（1-5億円、1-2年）"
        5: "非常に大きなリソース（>5億円、>2年）"

    - name: "timeline_estimate"
      description: "市場投入までの期間"
      weight: 0.3
      scoringGuide:
        1: "即座に開始可能（<3ヶ月）"
        2: "短期間で実現（3-6ヶ月）"
        3: "中期的な取り組み（6-18ヶ月）"
        4: "長期的なプロジェクト（18ヶ月-3年）"
        5: "非常に長期的（>3年）"

social_impact:
  dimension: "Social Impact"
  criteria:
    - name: "user_benefit"
      description: "エンドユーザーへの価値提供"
      weight: 0.4
      scoringGuide:
        1: "限定的な利便性向上"
        2: "一部ユーザーへの明確なメリット"
        3: "多くのユーザーの課題解決"
        4: "生活の質の大幅な向上"
        5: "社会生活の根本的な改善"

    - name: "societal_contribution"
      description: "社会全体への貢献度"
      weight: 0.3
      scoringGuide:
        1: "個人レベルでの小さな改善"
        2: "コミュニティレベルでの改善"
        3: "地域社会への明確な貢献"
        4: "国レベルでの社会課題解決"
        5: "グローバルな社会課題解決"

    - name: "sustainability"
      description: "環境・持続可能性への影響"
      weight: 0.3
      scoringGuide:
        1: "環境への影響は中立"
        2: "軽微な環境改善効果"
        3: "明確な環境保護効果"
        4: "大きな環境改善効果"
        5: "環境問題の抜本的解決"

strategic_alignment:
  dimension: "Strategic Alignment"
  criteria:
    - name: "vision_fit"
      description: "個人・組織のビジョンとの適合性"
      weight: 0.3
      scoringGuide:
        1: "ビジョンとの関連性が薄い"
        2: "部分的にビジョンと合致"
        3: "ビジョンの方向性と一致"
        4: "ビジョンの実現に大きく貢献"
        5: "ビジョンの中核的要素"

    - name: "skill_development"
      description: "スキル・知識の獲得機会"
      weight: 0.35
      scoringGuide:
        1: "既存スキルの範囲内"
        2: "軽微なスキル拡張"
        3: "新しい分野での学習機会"
        4: "専門性の大幅な向上"
        5: "革新的な能力の獲得"

    - name: "network_expansion"
      description: "人的ネットワークの拡大可能性"
      weight: 0.35
      scoringGuide:
        1: "既存の人脈内での活動"
        2: "関連分野での新しいつながり"
        3: "異分野での人脈構築"
        4: "業界キーパーソンとの関係構築"
        5: "グローバル・業界横断的なネットワーク"

# Overall impact calculation method
overall_calculation:
  method: "weighted_average"
  weights:
    business_value: 0.3
    implementation_feasibility: 0.25
    social_impact: 0.25
    strategic_alignment: 0.2

# Confidence scoring guidelines
confidence_levels:
  high: 0.8-1.0    # "十分な情報と実績に基づく確信"
  medium: 0.6-0.8  # "合理的な分析に基づく判断"
  low: 0.4-0.6     # "限定的な情報での推測"
  very_low: 0.1-0.4 # "非常に不確実な状況での仮説"

# Action item priority mapping
priority_mapping:
  urgent:     # overall_score >= 4.0 and confidence >= 0.7
    score_threshold: 4.0
    confidence_threshold: 0.7
    color: "red"

  high:       # overall_score >= 3.5 and confidence >= 0.6
    score_threshold: 3.5
    confidence_threshold: 0.6
    color: "orange"

  medium:     # overall_score >= 2.5 and confidence >= 0.5
    score_threshold: 2.5
    confidence_threshold: 0.5
    color: "yellow"

  low:        # below medium thresholds
    score_threshold: 0.0
    confidence_threshold: 0.0
    color: "gray"